config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_roles
  has_many :roles, through: :user_roles
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # regenerate this controller with
  # bin/rails generate hot_glue:scaffold User --gd --related-sets='roles' --include='name,roles' --smart-layout

  helper :hot_glue
  include HotGlue::ControllerHelper

  
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  after_action -> { flash.discard }, if: -> { request.format.symbol == :turbo_stream }
  
  
  def load_user
    @user = User.find(params[:id])
  end
  
  def load_all_users 
    @users = User.page(params[:page])
    
  end

  def index
    load_all_users
  end

  def new
    @user = User.new()
    
  end

  def create
    modified_params = modify_date_inputs_on_params(user_params.dup, nil, []) 

      
    
    @user = User.new(modified_params)
    
    

    if @user.save
      flash[:notice] = "Successfully created #{@user.name}"
      
      load_all_users
      render :create
    else
      flash[:alert] = "Oops, your user could not be created. #{@hawk_alarm}"
      @action = "new"
      render :create, status: :unprocessable_entity
    end
  end



  def show
    redirect_to edit_user_path(@user)
  end

  def edit
    @action = "edit"
    render :edit
  end

  def update
    flash[:notice] = +''
    flash[:alert] = nil
    

    modified_params = modify_date_inputs_on_params(update_user_params.dup, nil, []) 
    

    
      
    
    if @user.update(modified_params)
    
      
      flash[:notice] << "Saved #{@user.name}"
      flash[:alert] = @hawk_alarm if @hawk_alarm
      render :update
    else
      flash[:alert] = "User could not be saved. #{@hawk_alarm}"
      @action = "edit"
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    
    begin
      @user.destroy
      flash[:notice] = 'User successfully deleted'
    rescue StandardError => e
      flash[:alert] = 'User could not be deleted'
    end 
    load_all_users
  end



  def user_params
    params.require(:user).permit(:name, role_ids: [])
  end

  def update_user_params
    params.require(:user).permit(:name, role_ids: [])
  end

  def namespace
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_notices.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? && alert.nil? %>
    <div class="alert alert-<%= alert ? 'danger' : 'primary' %> alert-dismissible">
      <div><%= notice %></div>
      <div><%= alert %></div>
      <% if defined?(resource) && resource %>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HGUsersAndRoles2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <%= render partial: 'layouts/flash_notices' %>
  
    <%= yield %>
  </body>
</html>

app/views/users/_edit.erb
<%= turbo_frame_tag "__#{dom_id(user)}" do  %>
<div class="cell editable" style="position: relative;">
  <% if user.errors.any? %>
  <%= render(partial: "errors", locals: {resource: user }) %>
  <% end %>
  <h2>Editing <%= user.name %></h2>
  <%= form_with model: user, url: user_path(user) do |f| %>
  <%=  render partial: "users/form",  locals: {:user => user, f: f} %>
  <% end %>
</div>
<% end %>

app/views/users/_form.erb
<div class="row">
  <div class='col-md-2 cell--user--name' >  
    <span class='<%= "alert alert-danger" if user.errors.details.keys.include?(:name) %>'  style="display: inherit;"  >
       <br />
        <%= f.text_field :name, value: user.name, autocomplete: 'off', size: 40, class: 'form-control', type: '' %>
       
      
      <label class='text-muted small form-text' for=''>Name</label>
    </span>
    <br />
  </div>
  <div class='col-md-2 cell--user--roles' >  
    <span class='<%= "alert alert-danger" if user.errors.details.keys.include?(:roles) %>'  style="display: inherit;"  >
       <br />
       <%= f.collection_check_boxes :role_ids, Role.all, :id, :label, {} do |m| %>
            <%= m.check_box %> <%= m.label %><br />
          <% end %>
      <label class='text-muted small form-text' for=''>Roles</label>
    </span>
    <br />
  </div>

  <div class="col-md-2">
    <%= link_to "Cancel", users_path,  {class: "btn btn-secondary"} %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/users/_line.erb
<%= turbo_frame_tag "__#{ dom_id(user) }" do  %>
  <div class='row' data-id='<%= user.id %>' data-edit='false'>
    <%= render partial: 'users/show', locals: { user: user } %>

  </div>
<% end %>

app/views/users/_list.erb
<%= turbo_frame_tag "__users-list"   do %>
  <div class="container ">
    
      <h4>
        USERS
      </h4>
    

    <%= render partial: "users/new_button", locals: {} %><br />

    
      
        <div class="row ">
          <div class='col-sm-2 heading--user--name' >Name</div>
<div class='col-sm-2 heading--user--roles' >Roles</div>

          

          <div class=' scaffold-col-heading scaffold-col-heading-buttons col-sm-2' >
          </div>
        </div>
      

      <% if users.empty? %>
    <div>
        None
    </div>
      <% end %>
      <% users.each do |user| %>
        <%= render partial: 'users/line', locals: {user: user}
            .merge(defined?(nested_for) ? {nested_for: nested_for} : {})
      
        %>
      <% end %>
      
    <% if users.respond_to?(:total_pages) %><%= paginate(users) %> <% end %>
  
  </div>
<% end %>

app/views/users/_new_button.erb
<%= turbo_frame_tag "__user-new" do %>
  <div>
    <%= link_to "New User",  new_user_path, disable_with: "Loading...", class: "new-user-button btn btn-primary pull-right  " %>
  </div>
<% end %>

app/views/users/_new_form.erb
<%= turbo_frame_tag "__user-new" do %>
  <h3>
    New User
  </h3>
  <%= form_with model:  user, url: users_path, method: :post do  |f| %>
    <%=  render partial: "users/form",
locals: { user: user, f: f} %>
 <% end %>
<% end %>

app/views/users/_show.erb
<div class='col-sm-2 user--name'> <%= user.name %></div>
<div class='col-sm-2 user--roles'> <%= user.roles.collect(&:label).join(", ") %></div>






<div class=" scaffold-line-buttons col-md-2" >
  

  
    <%= form_with url: user_path(user), html: {data: {'turbo-confirm': "Are you sure you want to delete #{ user.name }?"}, style: "display: inline-block;"}, method: :delete do |f| %>
      <%= f.submit "Delete".html_safe,  class: "delete-user-button btn btn-primary btn-sm" %>
    <% end %>
  

  
  <%= link_to "Edit ".html_safe, edit_user_path(user), disable_with: "Loading...", class: "edit-user-button btn btn-primary btn-sm" %>
  
</div>

app/views/users/create.turbo_stream.erb
<% if @user.errors.none? %>
  <%= turbo_stream.replace "__users-list" + "" do %>
  <%= render partial: "list", locals: {users: @users} %>
  <% end %>
  <% end %>

  <%= turbo_stream.replace "__user-new" do %>
  <% if @user.errors.none? %>
  <%= render partial: "new_button", locals: {} %>
  <% else %>
  <%= render partial: "new_form", locals: {user: @user} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices", locals: {resource: @user} %>

<% end %>

app/views/users/destroy.turbo_stream.erb
<%= turbo_stream.update "__users-list" + "" do %>
  <%= render partial: "list", locals: {users: @users } %>
<% end %>

<%= turbo_stream.update "flash_notices" do %>
<%= render partial: "layouts/flash_notices", locals: {resource: @user} %>
<% end %>

app/views/users/edit.erb
<%= render partial: "edit", locals: {user: @user}  %>

app/views/users/edit.turbo_stream.erb
<%= turbo_stream.replace "__#{dom_id(user)}" do %>
  <%= render 'edit', locals: {user: @user %>
<% end %>

app/views/users/index.erb
<div class="container">
  <div class="row"> <div class="col-md-12">
  

  <%= render partial: 'users/list',
    locals: {users: @users} %>

  </div> </div>
</div>

app/views/users/new.erb
<%= render partial: "new_form", locals: {user: @user} %>

app/views/users/update.turbo_stream.erb
<%= turbo_stream.replace "__#{dom_id(@user)}" do %>
  <%= render partial: 'line', locals: {user: @user } %>
<% end %>

<%= turbo_stream.update "flash_notices" do %>
  <%= render partial: "layouts/flash_notices", locals: {resource: @user} %>
<% end %>

app/views/welcome/index.html.erb
Hello World